### PR TITLE
add sandbox ready counter to list routegroup

### PR DESCRIPTION
**Pull request by davixcky**
Fixes https://github.com/signadot/signadot/issues/3393

### CODE REVIEW

**Comment by davixcky** [comment]
PR updated with the changes on [main repo](https://github.com/signadot/signadot/issues/3393) discussion

**Review by scott-cotton — COMMENTED** [review]
When you say "small fork" does that mean forked from somewhere?  If so, what's the license?

**Comment by davixcky** [comment]
> When you say "small fork" does that mean forked from somewhere? If so, what's the license?
It doesn't explicitly say https://github.com/justincampbell/timeago

**Comment by davixcky** [comment]
> > > When you say "small fork" does that mean forked from somewhere? If so, what's the license?
> > 
> > 
> > It doesn't explicitly say https://github.com/justincampbell/timeago
> 
> In that case, can we just use it as an import? Then we aren't redistributing and hence open to all the questions around distributing license-less copies.


We changed a little bit. We remove the "about" and "over"

**Comment by scott-cotton** [comment]
> > > > When you say "small fork" does that mean forked from somewhere? If so, what's the license?
> > > 
> > > 
> > > It doesn't explicitly say https://github.com/justincampbell/timeago
> > 
> > 
> > In that case, can we just use it as an import? Then we aren't redistributing and hence open to all the questions around distributing license-less copies.
> 
> We changed a little bit. We remove the "about" and "over"

How about using https://pkg.go.dev/github.com/xeonx/timeago ?

**Review by scott-cotton — APPROVED** [review]
LGTM

**Pull request merged**
