### PR TITLE
Addition of jsonexact.Unmarshal() to disallow unknown fields from YAML definitions

### PR DESCRIPTION
**Pull request by daniel-de-vera**
Changes required to address issue [#2539](https://github.com/signadot/signadot/issues/2539)

### CODE REVIEW

**Comment by scott-cotton** [comment]
@daniel-de-vera do you think we should merge this before next release?

**Comment by scott-cotton** [comment]
> 
> In any case, I think the future path of the CLI (based on Anirudh's view) is not going to rely on this sort of checking client-side, so things will change.
> 
> If it were up to me, I would include it in the release.

I'm not sure it's incompatible with moving toward a thin client.  

I think it can be included and would help.

cc @foxish wdyt?

**Review by scott-cotton — APPROVED** [review]
LGTM, but also asked for @foxish 's take

**Comment by daniel-de-vera** [comment]
> > In any case, I think the future path of the CLI (based on Anirudh's view) is not going to rely on this sort of checking client-side, so things will change.
> > If it were up to me, I would include it in the release.
> 
> I'm not sure it's incompatible with moving toward a thin client.

No no, I don't think it is. What I was trying to say, is that writing a more complex logic than this client-side, to me is pointless given of the idea of moving toward a thin client.

**Comment by scott-cotton** [comment]
> > > In any case, I think the future path of the CLI (based on Anirudh's view) is not going to rely on this sort of checking client-side, so things will change.
> > > If it were up to me, I would include it in the release.
> > 
> > 
> > I'm not sure it's incompatible with moving toward a thin client.
> 
> No no, I don't think it is. What I was trying to say, is that writing a more complex logic than this client-side, to me is pointless given the idea of moving toward a thin client.

Agreed, but also I don't think such logic would be specific to the client, rather it would be independent of where it is used.

**Pull request merged**
